Remove requirement to install grub on server

diff --git a/bin/grub_client b/bin/grub_client
--- a/bin/grub_client
+++ b/bin/grub_client
@@ -5,7 +5,7 @@
 syntax()
 {
   echo "\
-Usage: grub_client [options] <client root> <server root> <server> <repo> <server build tool> <server Open Enterprise Foundation (OEF) dir>\n\
+Usage: grub_client [options] <client root> <server root> <server> <repo> <server Open Enterprise Foundation (OEF) dir>\n\
 Options:\n\
   -v | --verbose : print verbose output\n\
   -h | --help    : print this usage information\n\
@@ -20,8 +20,7 @@ where:\n\
   2: server_root       /u/fultonm/development\n\
   3: server            fultonm_zos\n\
   4: repo              asmdio\n\
-  5: server_build_tool /u/fultonm/grub/bin/grub_server\n\
-  6: server_oef_dir    /usr/lpp/IBM/foz/v1r1/bin\n\
+  5: server_oef_dir    /usr/lpp/IBM/foz/v1r1/bin\n\
 Note:\n\
   grub_client uses git and ssh to communicate with the remote server.\n\
   ssh should be configured with a public/private key and use a Host specification that includes at least a HostName and User specification.\n\
@@ -62,10 +61,9 @@ client_root=$1
 server_root=$2
 server=$3
 repo=$4
-remote_build_tool=$5
-remote_oef_dir=$6
+remote_oef_dir=$5
 
-if [[ $# -ne 6 ]]; then
+if [[ $# -ne 5 ]]; then
   syntax
   exit 4
 fi
@@ -204,13 +202,14 @@ seconds_sync=$(date '+%s')
 
 vecho "Repository synchronized:" $(date)
 
-vecho "Run build ${remote_build_tool} on ${server} in directory ${server_root}"
+client_dir="$(dirname "$(realpath "$0")")"
 
 bld_err="/tmp/grub.${server}_${repo}.err"
 bld_out="/tmp/grub.${server}_${repo}.out"
-ssh "${server}" ${remote_build_tool} "${server_root} ${repo} ${active_branch} ${remote_oef_dir} ${bld_out} ${bld_err}"
+
+cat $client_dir/grub_server | ssh "${server}" /bin/sh -s - "$server_root" "$repo" "$active_branch" "$remote_oef_dir" "$bld_out" "$bld_err"
 if [ $? -gt 0 ]; then
-  echo "ssh command <ssh ${server} ${remote_build_tool} ${server_root} ${repo} ${active_branch} ${remote_oef_dir} ${bld_out} ${bld_err}> failed.\n" >&2
+  echo "ssh command <ssh "${server}" /bin/sh -s - "$server_root" "$repo" "$active_branch" "$remote_oef_dir" "$bld_out" "$bld_err"> failed.\n" >&2
 fi
 
 seconds_build=$(date '+%s')
