add additional parameter to grub_server for OEF directory

diff --git a/bin/grub_server b/bin/grub_server
--- a/bin/grub_server
+++ b/bin/grub_server
@@ -8,18 +8,25 @@
 server_root="$1"
 repo="$2"
 active_branch="$3"
-bld_out="$4"
-bld_err="$5"
+oef_dir="$4"
+bld_out="$5"
+bld_err="$6"
 
 ME=$(basename $0)
 MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
 
 #
-# The following environment variables are required for
-# bash to run correctly. 
+# Add the oef_dir (Open Enterprise Foundation) directory 
+# for this server to the PATH so that bash and git can be located.
 #
 
-export PATH=/usr/lpp/IBM/foz/v1r1/bin:$PATH
+if [ -d "${oef_dir}" ] ; then
+  export PATH="${oef_dir}:$PATH"
+else
+  echo "Unable to set up Open Enterprise Foundation PATH with ${oef_dir}" >&2
+  exit 4
+fi
+
 export _BPXK_AUTOCVT=ON
 export _CEE_RUNOPTS="$_CEE_RUNOPTS FILETAG(AUTOCVT,AUTOTAG)"
 export _TAG_REDIR_ERR=txt
